declare module '@env' {
  const SENTRY_DSN: string;
  const FIREBASE_API_KEY_DEV: string;
  const FIREBASE_AUTH_DOMAIN_DEV: stringl;
  const FIREBASE_PROJECT_ID_DEV: string;
  const FIREBASE_STORAGE_BUCKET_DEV: string;
  const FIREBASE_MESSAGE_ID_DEV: string;
  const FIREBASE_APP_ID_DEV: string;
  const FIREBASE_MEASUREMENT_ID_DEV: string;
  export {
    SENTRY_DSN,
    FIREBASE_API_KEY_DEV,
    FIREBASE_AUTH_DOMAIN_DEV,
    FIREBASE_PROJECT_ID_DEV,
    FIREBASE_STORAGE_BUCKET_DEV,
    FIREBASE_MESSAGE_ID_DEV,
    FIREBASE_APP_ID_DEV,
    FIREBASE_MEASUREMENT_ID_DEV,
  };
}
